//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoSistemaEletoralEstudiantil.DataAccess.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EduVoteProEntities : DbContext
    {
        public EduVoteProEntities()
            : base("name=EduVoteProEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AuditLogs> AuditLogs { get; set; }
        public virtual DbSet<Elections> Elections { get; set; }
        public virtual DbSet<Parties> Parties { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<Votes> Votes { get; set; }
    }
}
