//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoSistemaEletoralEstudiantil.DataAccess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Votes
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public int PartyId { get; set; }
        public Nullable<System.DateTime> VoteDate { get; set; }
    
        public virtual Parties Parties { get; set; }
        public virtual Users Users { get; set; }
    }
}
